// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWithAzure.DataBaseConnection;

#nullable disable

namespace TestWithAzure.Migrations
{
    [DbContext(typeof(AzureDatabaseContext))]
    [Migration("20250128074932_Azure_UserBankDetails_Mst_addnew")]
    partial class Azure_UserBankDetails_Mst_addnew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestWithAzure.Models.UserBankDetails", b =>
                {
                    b.Property<int>("Pk_BankDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pk_BankDetailsId"));

                    b.Property<long>("AccountNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fk_Id")
                        .HasColumnType("int");

                    b.Property<string>("IFSC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pk_BankDetailsId");

                    b.HasIndex("Fk_Id");

                    b.ToTable("Azure_UserBankDetails_Mst");
                });

            modelBuilder.Entity("TestWithAzure.Models.UserInformation", b =>
                {
                    b.Property<int>("Pk_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pk_Id"));

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pk_Id");

                    b.ToTable("Azure_UserInformation_Mst");
                });

            modelBuilder.Entity("TestWithAzure.Models.UserBankDetails", b =>
                {
                    b.HasOne("TestWithAzure.Models.UserInformation", "_userInformation")
                        .WithMany()
                        .HasForeignKey("Fk_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_userInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
